### ISSUE TITLE
Feature request: Allow gotz to remain opened and update continuously

### ISSUE THREAD

**Issue by cuongvo** [merschformann/gotz#1]
I'd like to keep gotz opened and glance at it without running the command. Ideally this is a flag or configuration value with maybe a sane update interval that can also be configured. I don't need 60 FPS for this, for example, or even every second. Minutes?

**Comment by merschformann** [comment]
On Linux I would simply use `watch gotz`, but that probably does not work across platforms. [This](https://github.com/gdamore/tcell) looks interesting and may support it. Will look at it a bit more and see whether it can somewhat easily be done. :relaxed:

**Comment by merschformann** [comment]
Implemented by #2
(enable via `--live true`)
