### ISSUE TITLE
Inline Timezone Bars?

### ISSUE THREAD

**Issue by KyleKing** [merschformann/gotz#13]
Would it be possible to have the bars shown inline with the labels? I find it hard to read when the bars are underneath. Maybe something like this:

```sh
                                                                   now v 07:47
                                                                        | 
Local : Thu 28 Jul 2022 07:47                               ▒▒▒▒▒▒████████████████████████████████████████████████▒▒▒▒▒▒▒▒▒▒▒▒
                                                                        | 
SF    : Thu 28 Jul 2022 07:47                            ﻿﻿▒▒▒▒▒▒████████████████████████████████████████████████▒▒▒▒▒▒▒▒▒▒▒▒
                                                                        | 
IST   : Thu 28 Jul 2022 20:17 ▒▒▒▒▒████████████████████████████████████████████████▒▒▒▒▒▒▒▒▒▒▒▒      
```

**Comment by merschformann** [comment]
Yeah, sounds like a good idea. I am curious whether the empty line is necessary. Or maybe it's an option. :thinking: 
Let me give it a try and come back here. :relaxed:

**Comment by merschformann** [comment]
Maybe something like this? I really like how dense it is, and I think you're right about improved readability.
![draft](https://user-images.githubusercontent.com/11454283/181658255-f62e43e3-d458-437f-8b71-658be6d207d6.png)

I put up a draft PR at #14. You can install it via `go install .` after checking out the branch, if you like to play with it. Or just let me know what you think about the concept.

I am not sure about the additional lines, they could be another option. :thinking: I will play around with it some more during the weekend and finalize it.

**Comment by KyleKing** [comment]
Awesome! Thanks for building that so quickly. Looks great to me!

These are the two terminal editor widths I typically use:

<img width="1437" alt="Screen Shot 2022-07-29 at 07 16 46" src="https://user-images.githubusercontent.com/3784339/181781788-5e126a27-8778-45c7-82e5-c15208306489.png">

<img width="715" alt="Screen Shot 2022-07-29 at 07 16 29" src="https://user-images.githubusercontent.com/3784339/181781796-d3dda22b-ee04-42eb-a33f-d833a00f5836.png">

and my config (TBD on setting colors!):

<details>
<summary>Details</summary> 
<div class="highlight highlight-source-json position-relative"><pre>
{
  "config_version": "1.0",
  "hours12": false,
  "inline": true,
  "live": false,
  "stretch": false,
  "style": {
    "coloring": {
      "DynamicColorBackground": "",
      "DynamicColorDay": "",
      "DynamicColorEvening": "",
      "DynamicColorForeground": "",
      "DynamicColorMorning": "",
      "DynamicColorNight": "",
      "StaticColorDay": "",
      "StaticColorEvening": "",
      "StaticColorForeground": "",
      "StaticColorMorning": "",
      "StaticColorNight": ""
    },
    "colorize": true,
    "day_segments": {
      "day": 9,
      "evening": 17,
      "morning": 8,
      "night": 19
    },
    "symbols": "rectangles"
  },
  "tics": false,
  "timezones": [
    {
      "Name": "SF",
      "TZ": "America/Santa_Isabel"
    },
    {
      "Name": "IST",
      "TZ": "Asia/Calcutta"
    },
    {
      "Name": "France",
      "TZ": "Arctic/Longyearbyen"
    }
  ]
}
</pre></div>
</details>

**Comment by merschformann** [comment]
Great! I think I will skip on the extra lines for now. Still time to add it later, if it feels missing.
Also, I changed the default to inline, since it indeed feels more readable. I hope the majority agrees. :relaxed:

**Comment by merschformann** [comment]
#14 is merged and a new release is out. Let me know, if all works @KyleKing. :relaxed:

**Comment by KyleKing** [comment]
This is awesome! I removed the local versions, made a fresh installation, and it works. Thanks!
