### ISSUE TITLE
Aggressive Config File Behavior

### ISSUE THREAD

**Issue by MS3FGX** [merschformann/gotz#4]
I like the idea of creating a known-good config file at startup, but replacing the user's custom config file with the defaults when a syntax error has been found seems very aggressive. It means the user is just one typo away from having their carefully tailored configuration getting blown away without warning. Since I'm posting this, I bet you can probably guess what just happened to me...

It seems safer behavior would simply be to exit with an error message if the configuration file cannot be parsed. At the very least, the user should be given the chance to cancel before their custom configuration is replaced.

**Comment by merschformann** [comment]
Yeah, I had a similar feeling while writing it. I should have gone with my gut and solved it differently. I was in a bit of a hurry back then. :sweat_smile: 

Would it make sense to show an error and offer the user the option to reset the config?

**Comment by merschformann** [comment]
Also, thank you for the feedback! :hugs:

**Comment by merschformann** [comment]
I hope #5 works as a fix. :relaxed:

**Comment by MS3FGX** [comment]
Appreciate the quick resolution, looks good to me.
