### ISSUE TITLE
missing tzdata for windows release

### ISSUE THREAD

**Issue by endowdly** [merschformann/gotz#8]
gotz doesn't output correctly on the windows release (and I _think_ I know why).

Here is a screenshot of a default configuration running with the local time being Eastern Standard:

![image](https://user-images.githubusercontent.com/12169947/169434737-1a81b68c-1ace-42ff-9378-235486fd59e7.png)

Here is a command-line bork on a manual entry:

![image](https://user-images.githubusercontent.com/12169947/169434822-ae8799a6-2ca7-4956-a81f-b689ba34c2aa.png)

Now, I'm not a go developer but it's a lovely language and easy to follow. In [configuration.go](https://github.com/merschformann/gotz/blob/main/core/configuration.go#L99) and in [args.go](https://github.com/merschformann/gotz/blob/main/core/args.go#L217) there is use of the `time::Location.LoadLocation(name)` function. 

[Docs](https://pkg.go.dev/time?GOOS=windows#LoadLocation) state:

> LoadLocation looks for the IANA Time Zone database in the following locations in order:

> - the directory or uncompressed zip file named by the ZONEINFO environment variable - on a Unix system, the system standard installation location - $GOROOT/lib/time/zoneinfo.zip - the time/tzdata package, if it was imported.

Windows doesn't have an IANA database and also doesn't run a ZONEINFO env var. But, what's this about [time/tzdata](https://pkg.go.dev/time/tzdata@go1.18.2)?

> This package will be automatically imported if you build with -tags timetzdata.

I think the easiest fix is in your [build](https://github.com/merschformann/gotz/blob/main/material/scripts/buildall.sh) script, if you add `-tags timetzdata` to line 23? Maybe you don't want to do that for unix systems, maybe add another variable and add it with the name change on line 19? 

In any case, I love simple TUI command-line tools and yours is spiffy. I love using them as practice to learn or reinforce languages and I'm porting gotz to .NET in F# and C# and I hope to have the F# port done in another day or so.  :)

**Comment by merschformann** [comment]
Good point. I think it's worth integrating the data directly in any case. Thank you for collecting the information!

Can you check whether this binary solves your problem?

[gotz_windows.zip](https://github.com/merschformann/gotz/files/8739079/gotz_windows.zip)

Or you can run the buildscript from #9 to compile yourself.

Also, I fully agree with implementing small projects for learning a new language. :relaxed:

**Comment by endowdly** [comment]
I tried the binary you compiled and ran a local build -- both success! 

Excellent work overall. Closing #8.

(Your repos are all a pleasure to read through. I love sardine-can and geomove. Finally, someone else who understands the pain of calculating through great circle distance.)
